# Generated by Django 2.2.18 on 2021-12-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_info', '0002_auto_20211220_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain_info',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='domain_info',
            name='directories',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='domain_info',
            name='ip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='domain_info',
            name='lookup',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domain_info',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='domain_info',
            name='technology',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='domain_info',
            name='urls',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
